# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/harun/Documents/MP/MP_DEMO_COMBINED/MP_DEMO_COMBINED.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0.xci
# IP: The module: 'design_1_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/harun/Documents/MP/MP_DEMO_COMBINED/MP_DEMO_COMBINED.srcs/sources_1/bd/system/system.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: C:/Users/harun/Documents/MP/MP_DEMO_COMBINED/MP_DEMO_COMBINED.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: C:/Users/harun/Documents/MP/MP_DEMO_COMBINED/MP_DEMO_COMBINED.srcs/sources_1/bd/system/ip/system_rst_pixel_74m_0/system_rst_pixel_74m_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_pixel_74m_0 || ORIG_REF_NAME==system_rst_pixel_74m_0} -quiet] -quiet

# IP: C:/Users/harun/Documents/MP/MP_DEMO_COMBINED/MP_DEMO_COMBINED.srcs/sources_1/bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_data_fifo_0_0 || ORIG_REF_NAME==system_axis_data_fifo_0_0} -quiet] -quiet

# IP: C:/Users/harun/Documents/MP/MP_DEMO_COMBINED/MP_DEMO_COMBINED.srcs/sources_1/bd/system/ip/system_rgb2dvi_0_0/system_rgb2dvi_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rgb2dvi_0_0 || ORIG_REF_NAME==system_rgb2dvi_0_0} -quiet] -quiet

# IP: C:/Users/harun/Documents/MP/MP_DEMO_COMBINED/MP_DEMO_COMBINED.srcs/sources_1/bd/system/ip/system_const_vcc_0/system_const_vcc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_const_vcc_0 || ORIG_REF_NAME==system_const_vcc_0} -quiet] -quiet

# XDC: c:/Users/harun/Documents/MP/MP_DEMO_COMBINED/MP_DEMO_COMBINED.gen/sources_1/bd/system/system_ooc.xdc

# IP: C:/Users/harun/Documents/MP/MP_DEMO_COMBINED/MP_DEMO_COMBINED.srcs/sources_1/bd/design_1/ip/design_1_top_0_0/design_1_top_0_0.xci
# IP: The module: 'design_1_top_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: C:/Users/harun/Documents/MP/MP_DEMO_COMBINED/MP_DEMO_COMBINED.srcs/sources_1/bd/system/system.bd
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system || ORIG_REF_NAME==system} -quiet] -quiet

# IP: C:/Users/harun/Documents/MP/MP_DEMO_COMBINED/MP_DEMO_COMBINED.srcs/sources_1/bd/system/ip/system_clk_wiz_0_0/system_clk_wiz_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_clk_wiz_0_0 || ORIG_REF_NAME==system_clk_wiz_0_0} -quiet] -quiet

# IP: C:/Users/harun/Documents/MP/MP_DEMO_COMBINED/MP_DEMO_COMBINED.srcs/sources_1/bd/system/ip/system_rst_pixel_74m_0/system_rst_pixel_74m_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rst_pixel_74m_0 || ORIG_REF_NAME==system_rst_pixel_74m_0} -quiet] -quiet

# IP: C:/Users/harun/Documents/MP/MP_DEMO_COMBINED/MP_DEMO_COMBINED.srcs/sources_1/bd/system/ip/system_axis_data_fifo_0_0/system_axis_data_fifo_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_axis_data_fifo_0_0 || ORIG_REF_NAME==system_axis_data_fifo_0_0} -quiet] -quiet

# IP: C:/Users/harun/Documents/MP/MP_DEMO_COMBINED/MP_DEMO_COMBINED.srcs/sources_1/bd/system/ip/system_rgb2dvi_0_0/system_rgb2dvi_0_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_rgb2dvi_0_0 || ORIG_REF_NAME==system_rgb2dvi_0_0} -quiet] -quiet

# IP: C:/Users/harun/Documents/MP/MP_DEMO_COMBINED/MP_DEMO_COMBINED.srcs/sources_1/bd/system/ip/system_const_vcc_0/system_const_vcc_0.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==system_const_vcc_0 || ORIG_REF_NAME==system_const_vcc_0} -quiet] -quiet

# XDC: c:/Users/harun/Documents/MP/MP_DEMO_COMBINED/MP_DEMO_COMBINED.gen/sources_1/bd/system/system_ooc.xdc
